#!/usr/bin/env bash

set -e

### constants ##################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### variables ##################################################################

registry_url="$1"
release_name="$(cat "$this_path/release_name")"
release_name=$(echo "$release_name" | tail -n1)

### release ####################################################################

if [ -z "$registry_url" ]; then
  echo "Usage: $0 REGISTRY_URL"
  echo ""
  echo "  e.g.: $0 https://your.registry.com:5000/rfdocker"
  exit 64
fi

echo "### Tagging image 'rfdocker:$release_name' to '$registry_url:$release_name'"
docker tag "rfdocker:$release_name" "$registry_url:$release_name"

echo "### Pushing image 'rfdocker:$release_name' to registry..."
docker push "$registry_url:$release_name"

echo "### Tagging image 'rfdocker:$release_name' to '$registry_url:latest'"
docker tag "rfdocker:$release_name" "$registry_url:latest"

echo "### Pushing image 'rfdocker:$release_name' to '$registry_url:latest'"
docker push "$registry_url:latest"

echo "### Creating a git tag '$release_name' for release"
git tag --force --annotate --message "Release $release_name" "$release_name"

echo "### To push git tag '$release_name':"
echo ""
echo "  git push origin $release_name"
echo ""
